---
# mysql installation
- name: set mysql_server_id based on ip address
  set_fact: mysql_server_id={{ ansible_default_ipv4.address|regex_replace("^.{0,3}|[.]") }}
  when: mysql_server_id is not defined

- name: install mysql
  apt: pkg={{ item }} state=installed
  register: mysql_install
  with_items: mysql_packages

- name: configure mysql
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf owner=root group=root mode=0644
  notify: restart mysql

- name: start and enable
  service: name=mysql state=started enabled=yes

- name: set root password
  mysql_user: name=root password="{{ mysql_root_password }}" state=present priv=*.*:ALL,GRANT
  when: mysql_root_password is defined or mysql_install.changed

  # required to properly update root password
- name: update password
  template: src=client_options.j2 dest=~/.my.cnf owner=root group=root mode=0600
  when: mysql_root_password is defined or mysql_install.changed

- name: enable users
  when: mysql_users is defined
  with_dict: mysql_users
  mysql_user:
    name="{{item.key}}"
    host="{{item.value.host}}"
    password="{{item.value.password}}"
    priv="{{item.value.privileges}}"
    state=present

- name: open mysql port
  ufw: rule=allow port={{item}} proto=tcp
  with_items: "{{firewall_open}}"

